const CHANGE_ANGULAR_POSE_STATE = 'CHANGE_ANGULAR_POSE_STATE';
const CHANGE_REACT_STATE = 'CHANGE_REACT_STATE';
const CHANGE_VUE_STATE = 'CHANGE_VUE_STATE';
const CHANGE_CUSTOM_STATE = 'CHANGE_CUSTOM_STATE';

export default {
  CHANGE_ANGULAR_POSE_STATE,
  CHANGE_CUSTOM_STATE,
  CHANGE_REACT_STATE,
  CHANGE_VUE_STATE
}